### ISSUE TITLE
Detailed `README.md` wanted

### ISSUE THREAD

**Issue by ITPini** [PrometheusBork/AI-RTS-PROJECT#24]
## Issue Description
Missing `README.md` wanted for our repository, the existing does not include sections like installation, usage, contributing and etc. 

## Expected Behavior
A `README.md` should be included in most repository, some sections that the `README.md` could cover are:
1. **Installation**: Step-by-step instructions on how to set up the project locally
2. **Usage**: Examples of how to use the project after installation
3. **Contributing**: As this is a open source project for our bachelor, we could include coding standards, branch naming conventions and pull request process for others who should be interested in continuing this project.

## Actual Behavior
Currently, the `README.md` file is empty.

**Comment by PrometheusBork** [comment]
I have written some things for the readme and pushed directly to dev 😸 It is not final but now we have something atleast

**Comment by PrometheusBork** [comment]
Btw I am also unsure of the packages required

**Comment by ITPini** [comment]
Fixed in commit 5e31504
