### ISSUE TITLE
Tree image is not removed when Tree object is removed

### ISSUE THREAD

**Issue by PrometheusBork** [PrometheusBork/AI-RTS-PROJECT#4]
## Issue Description
There is an issue with the image from the tree object not being removed when the tree object is removed

## Expected Behavior
The tree image should not be visible anymore when the tree object is removed

## Actual Behavior
![image](https://github.com/PrometheusBork/AI-RTS-PROJECT/assets/100210077/822ec2d6-0ced-45e4-baf5-0daabbc9fe7e)

## Proposed Solution
It may be a problem with the renderer I do not know the solution yet

**Comment by ITPini** [comment]
This is likely the cause of the game object being removed from the `Tile` object but not removed from the `SpriteManager` class. Creating a `DestructionManager` that manages destruction and interaction with `SpriteManager` might be necessary. In that way, we can also remove the responsibility of damaging objects away from the `MovementManager`

**Comment by PrometheusBork** [comment]
I will try to fix this then
